version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore
build_script:
  - cmd: dotnet build --configuration Release
test_script:
  - cmd: dotnet test